<a href="https://colab.research.google.com/github/slawa-pro/pytorchProject/blob/main/test_training_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Sun Jul  6 16:33:51 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import torch
from torch.nn import ReLU, Sigmoid, Softmax

In [ ]:
x = torch.tensor([[6.4],[3.4],[1.2]])
layer = Sigmoid();
print(layer(x))

tensor([[0.9983],
        [0.9677],
        [0.7685]])


In [1]:
import torch
from torch.nn import Sequential, Linear, ReLU, Sigmoid, Softmax

X = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])

model1 = Sequential(
    Linear(3, 16),
    ReLU(),
    Linear(16, 32),
    ReLU(),
    Linear(32, 5),
    Softmax(),
)
print(model1(X))

model2 = Sequential(
    Linear(3, 32),
    ReLU(),
    Linear(32, 32),
    ReLU(),
    Linear(32, 1),
)
print(model2(X))

model3 = Sequential(
    Linear(3, 16),
    ReLU(),
    Linear(16, 1),
    Sigmoid(),
)
print(model3(X))


tensor([[0.1383, 0.2589, 0.2024, 0.0949, 0.3054],
        [0.0846, 0.2547, 0.2140, 0.0422, 0.4044],
        [0.0441, 0.2234, 0.2051, 0.0166, 0.5107]], grad_fn=<SoftmaxBackward0>)
tensor([[0.1098],
        [0.2064],
        [0.3629]], grad_fn=<AddmmBackward0>)
tensor([[0.6935],
        [0.8161],
        [0.8965]], grad_fn=<SigmoidBackward0>)


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1739: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
