<a href="https://colab.research.google.com/github/slawa-pro/pytorchProject/blob/main/test_training_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Sun Jul  6 16:33:51 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
import torch
x = torch.tensor([[0.4, 0.5],[0.9, 0.2],[0.2, 0.0],[0.1, 0.0]])
w = torch.tensor([[0.4, 0.5, 1.3],[0.9, 0.2, 0.4]])
print(x @ w)

tensor([[0.6100, 0.3000, 0.7200],
        [0.5400, 0.4900, 1.2500],
        [0.0800, 0.1000, 0.2600],
        [0.0400, 0.0500, 0.1300]])


In [9]:
import torch
from torch.nn import Linear

x = torch.tensor([[0.4, 0.5], [0.9, 0.2], [0.2, 0.0], [0.1, 0.0]], dtype=torch.float32)
# количество признаков на входе и выходе
layer = Linear(2, 3)

# матрица весов нового линейного слоя
print(layer(x))

tensor([[ 0.0786,  0.6823,  0.1728],
        [-0.2119,  0.6035,  0.1719],
        [-0.0937,  0.4678,  0.4803],
        [-0.0635,  0.4598,  0.5102]], grad_fn=<AddmmBackward0>)


In [11]:
import torch
from torch.nn import ReLU, Sigmoid, Softmax

x = torch.tensor([[0.4, 0.5, -0.2], [0.9, 0.2, -1.2], [0.2, -0.1, 2.1]])
#между ленейными слоями используют функция ReLU для активации
layer = ReLU()
print(x)
print(layer(x))

tensor([[ 0.4000,  0.5000, -0.2000],
        [ 0.9000,  0.2000, -1.2000],
        [ 0.2000, -0.1000,  2.1000]])
tensor([[0.4000, 0.5000, 0.0000],
        [0.9000, 0.2000, 0.0000],
        [0.2000, 0.0000, 2.1000]])


In [12]:
import torch
from torch.nn import ReLU, Sigmoid, Softmax

x = torch.tensor([[6.7], [-3.2], [1.1]])
#после последнего слоя используют функцию Sigmoid
layer = Sigmoid()
print(x)
print(layer(x))

tensor([[ 6.7000],
        [-3.2000],
        [ 1.1000]])
tensor([[0.9988],
        [0.0392],
        [0.7503]])


In [14]:
import torch
from torch.nn import ReLU, Sigmoid, Softmax

x = torch.tensor([[0.4, 0.5, -0.2], [0.9, 0.2, -1.2], [0.2, -0.1, 2.1]])
#в каждой строке побеждает то значение которое было максимально изначально
layer = Softmax()
print(x)
print(layer(x))

tensor([[ 0.4000,  0.5000, -0.2000],
        [ 0.9000,  0.2000, -1.2000],
        [ 0.2000, -0.1000,  2.1000]])
tensor([[0.3768, 0.4164, 0.2068],
        [0.6176, 0.3067, 0.0756],
        [0.1187, 0.0879, 0.7934]])


In [16]:
import torch
from torch.nn import ReLU, Sigmoid, Sequential

x = torch.tensor([[0.4, 0.5, -0.2], [0.9, 0.2, -1.2], [0.2, -0.1, 2.1]])
#модель для регрессии
model = Sequential(
    Linear(3, 10),
    ReLU(),
    Linear(10, 20),
    ReLU(),
    Linear(20, 1),
)
print(model(x))

tensor([[-0.0757],
        [-0.0269],
        [-0.0487]], grad_fn=<AddmmBackward0>)


Linear(3, 10):

Умножает входной тензор x (размер [3, 3]) на матрицу весов [3, 10].

Формула: y = x @ W.T + b, где W — веса, b — смещение.

ReLU():

Активация: max(0, x) (обнуляет отрицательные значения).

Последовательность слоёв:

Данные проходят через все слои по очереди (Sequential).

Выход:

Размерность: [3, 1] (по одному предсказанию для каждого из 3 примеров).

